spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbtest
    username: root
    password: 123456
#配置日志
logging:
  #配置日志文件路径
  path: E:\ideagit\pfdistribution
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
